Document: helium-mobile-browser
Title: Debian helium-mobile-browser Manual
Author: <insert document author here>
Abstract: This manual describes what helium-mobile-browser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/helium-mobile-browser/helium-mobile-browser.sgml.gz

Format: postscript
Files: /usr/share/doc/helium-mobile-browser/helium-mobile-browser.ps.gz

Format: text
Files: /usr/share/doc/helium-mobile-browser/helium-mobile-browser.text.gz

Format: HTML
Index: /usr/share/doc/helium-mobile-browser/html/index.html
Files: /usr/share/doc/helium-mobile-browser/html/*.html
